### ISSUE TITLE
Enabling NChat for Guest accounts

### ISSUE THREAD

**Issue by melwynjensen** [nvcnvn/NChat#1]
Hi,

Can you please tell me how to enable the NChat for guest accounts as well? Is it possible to do it?

**Comment by nvcnvn** [comment]
Hi,

Can you try go to AdminCP > Member Permission and check the permission for guest?
Does it show this image: http://custom.simplemachines.org/mods/index.php?action=download;mod=2846;id=189326;image

**Comment by melwynjensen** [comment]
Oops.. sorry for my ignorance as I am new to SMF! Changed the permission and it's working fine now :)
